name: pita
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- biofluff
- biopython
- gimmemotifs
- bcbiogff
- pysam
- pyyaml
- networkx
- htseq
- sqlalchemy
- pytest
- maxentpy
- rpy2
- r-changepoint
- samtools
- stringtie

