#!/usr/bin/env python
import sys
import os
import argparse
from pita.utr import *
from pkg_resources import require
version = require("pita")[0].version


import pkg_resources
version = pkg_resources.require("pita")[0].version

p = argparse.ArgumentParser()
p.add_argument("-i",
                dest= "bedfile",
                help="genes in BED12 format",
              )
p.add_argument("-b",
                dest= "bamfiles",
                help="list of RNA-seq BAM files (seperated by space)",
                nargs="+"
              )
p.add_argument("-v",
                action='store_true',
                dest="version",
                help="Print the program version and exit",
                required=False
              )

args = p.parse_args()

if args.version:
    print("Version: "+version)
    sys.exit()

if not args.bedfile or not args.bamfiles:
    p.print_help()
    sys.exit()

bedfile = args.bedfile
bamfiles = args.bamfiles

for bamfile in bamfiles:
    if not os.path.exists(bamfile):
        sys.stderr.write("BAM file {} does not exist.\n".format(bamfile))
        sys.exit(1)    
    if not os.path.exists(bamfile + ".bai"):
        sys.stderr.write("index file {}.bai does not exist.\n".format(bamfile))
        sys.exit(1)

if not os.path.exists(bedfile):
    sys.stderr.write("BED file {} does not exist.\n".format(bedfile))
    sys.exit(1)

print_updated_bed(bedfile, bamfiles)
