#!/usr/bin/env python
import sys
import os
import argparse
from pita.utr import *

p = argparse.ArgumentParser()
p.add_argument("-i",
               dest= "bedfile",
               help="genes in BED12 format",
              )
p.add_argument("-b",
               dest= "bamfiles",
               help="list of RNA-seq BAM files (seperated by comma)",
              )
args = p.parse_args()

if not args.bedfile or not args.bamfiles:
    p.print_help()
    sys.exit()

bedfile = args.bedfile
bamfiles = args.bamfiles.split(",")

for bamfile in bamfiles:
    if not os.path.exists(bamfile):
        sys.stderr.write("BAM file {} does not exist.\n".format(bamfile))
        sys.exit(1)    
    if not os.path.exists(bamfile + ".bai"):
        sys.stderr.write("index file {}.bai does not exist.\n".format(bamfile))
        sys.exit(1)

if not os.path.exists(bedfile):
    sys.stderr.write("BED file {} does not exist.\n".format(bedfile))
    sys.exit(1)

print_updated_bed(bedfile, bamfiles)
